events {
    worker_connections 1024;
}

http {
    upstream patients-service {
        server patients-service:8080;
    }
    upstream personnel{
        server personnel-api-8080;
    }

    server {
        listen 80;

        location /api/patients {
            proxy_pass http://patients-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/personnel{
        proxy_pass http:://personnel/;
        }
    }
}