<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="ValuedObjects\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\patients-service\src\LifeCare.Patients.Domain\LifeCare.Patients.Domain.csproj"/>
    </ItemGroup>

</Project>
