<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\LifeCare.Modules.Shared.Domain.csproj" />
    <ProjectReference Include="..\Application\LifeCare.Modules.Shared.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
